version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  configuration:
    image: training/configuration
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - SLEEP_TIME=5
      - DEFAULT_PROFILE=production
  discovery:
    image: training/discovery
    ports:
      - "8089:8089"
    environment:
      - CONFIG_SERVER=configuration
      - CONFIG_SERVER_PORT=8888
      - SLEEP_TIME=5
      - DEFAULT_PROFILE=production
  gateway:
    image: training/gateway
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER=configuration
      - CONFIG_SERVER_PORT=8888
      - SLEEP_TIME=5
      - DEFAULT_PROFILE=production
  departments-database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=departments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/departments
    volumes:
      - ./data/daprtments:/var/lib/postgresql/data/departments
  users-database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/users
    volumes:
      - ./data/users:/var/lib/postgresql/data/users
  users:
    image: training/users
    environment:
      - CONFIG_SERVER=configuration
      - CONFIG_SERVER_PORT=8888
      - SLEEP_TIME=5
      - DEFAULT_PROFILE=production
  departments:
    image: training/departments
    environment:
      - CONFIG_SERVER=configuration
      - CONFIG_SERVER_PORT=8888
      - SLEEP_TIME=5
      - DEFAULT_PROFILE=production
